nameOverride: ""
fullnameOverride: pinstack-ingress

serviceAccount:
  create: false
  name: ""

ingress:
  className: nginx
  annotations: {}
  path: /
  pathType: Prefix
  backendService:
    name: api-gateway
    port: 8080
