{{- if .Values.postgres.passwordSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.passwordSecret.name }}
  labels:
    {{- include "user-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.passwordSecret.key }}: {{ .Values.postgres.passwordSecret.value | quote }}
{{- end }}

