replicaCount: 3

nameOverride: ""
fullnameOverride: kafka

image:
  repository: confluentinc/cp-kafka
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 9092
  controllerPort: 9093

kraft:
  clusterId: MkU3OEVBNTcwNTJENDM2Qk

kafka:
  autoCreateTopicsEnable: "false"
  log4jRootLoglevel: WARN
  toolsLog4jLoglevel: WARN
  heapOpts: "-Xmx1G -Xms1G"

topicsInit:
  enabled: true
  image:
    repository: confluentinc/cp-kafka
    tag: latest
    pullPolicy: IfNotPresent
  bootstrapServers: kafka:9092
  waitSeconds: 10
  topics:
    - name: relation-events
      partitions: 3
      replicationFactor: 3
    - name: notifications
      partitions: 3
      replicationFactor: 3
  backoffLimit: 3
  activeDeadlineSeconds: 240
  ttlSecondsAfterFinished: 300

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10

nodeSelector: {}
tolerations: []

affinity: {}
