replicaCount: 1

nameOverride: ""
fullnameOverride: user-db

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 5432

postgres:
  user: postgres
  database: userservice
  port: 5432
  passwordSecret:
    create: true
    name: user-db-secret
    key: password
    value: admin

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6

nodeSelector: {}
tolerations: []

affinity: {}
