replicaCount: 2

nameOverride: ""
fullnameOverride: post-service

image:
  repository: pinstack/post-service
  tag: "dev"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 50053

env:
  ENV: dev

db:
  host: post-db
  port: "5432"
  name: postservice
  user: postgres
  passwordSecret:
    name: post-db-secret
    key: password

migrator:
  enabled: true
  image:
    repository: pinstack/post-migrator
    tag: "dev"
    pullPolicy: IfNotPresent
  command:
    - ./migrator
    - -command
    - up
  backoffLimit: 3
  activeDeadlineSeconds: 180
  ttlSecondsAfterFinished: 300
  volumeMounts:
    - name: post-config
      mountPath: /app/config
      readOnly: true
    - name: post-migrations
      mountPath: /app/migrations
      readOnly: true
  volumes:
    - name: post-config
      configMap:
        name: post-service-config
    - name: post-migrations
      configMap:
        name: post-service-migrations

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6

volumes:
  - name: post-config
    configMap:
      name: post-service-config
volumeMounts:
  - name: post-config
    mountPath: /app/config
    readOnly: true

nodeSelector: {}
tolerations: []

affinity: {}
