replicaCount: 2

nameOverride: ""
fullnameOverride: auth-service

image:
  repository: pinstack/auth-service
  tag: "dev"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 50052

env:
  ENV: dev

db:
  host: auth-db
  port: "5432"
  name: authservice
  user: postgres
  passwordSecret:
    name: auth-db-secret
    key: password

migrator:
  enabled: true
  image:
    repository: pinstack/auth-migrator
    tag: "dev"
    pullPolicy: IfNotPresent
  command:
    - ./migrator
    - -command
    - up
  backoffLimit: 3
  activeDeadlineSeconds: 180
  ttlSecondsAfterFinished: 300

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []

affinity: {}
